[package]
name = "izhikevich-neurons"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
edition = "2018"

[dependencies]
closed01 = "0.5"

[dev-dependencies]
gnuplot = "0.0.30"
rand = "0.6"
